version: '2'
services:
  database:
    build: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  app:
    build: app
    depends_on: [database]
    links:
      - database
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:password@database:3305/posterr?charset=utf8mb4'
